logo: https://bioboot.github.io/bggn213_W25/assets/img/logo.png
title: Nancy's Bioinformatics Class Winter 2025 
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
