---
title: "Class 12 AlphaFold analysis"
author: "Nancy Leon Rivera"
format: pdf
---
Here we demonstrate how to analyze and make sense of models from AlphFold. We begin by reading all the model PDB files...


```{r}
library(bio3d)

```
PDB file names of my models
```{r}
files <- list.files("hiv_monomer_94b5b/", pattern = ".pdb", full.names = T)
files


```

#Align and superimpose
```{r}
pdbs <- pdbaln(files, fit = TRUE, exefile="msa")

```


RMSD analysis

```{r}
rd <- rmsd(pdbs)
mean(rd)
```


```{r}
source("http://tinyurl.com/newviewngl")
library(NGLVieweR)
#view.pdbs(pdbs)
```



##PCA



```{r}
pc <- pca(pdbs)
  plot(pc)
```


#Residues conservation from alignment file

AlphaFold writes out the MSA it calcualted 
```{r}
aln_file <- list.files(path="hiv_monomer_94b5b/", pattern = ".a3m$", full.names = TRUE)
aln_file
```


```{r}
aln <- read.fasta(aln_file, to.upper=T)
```



```{r}
dim(aln$ali)
```
```{r}
sim <- conserv(aln)

```

```{r}
con <- consensus(aln, cutoff = 0.9)
con$seq
```




```{r}
plot(sim, type ="h")

```

```{r}
#pdb <- read.pdb( files[1])
#view.pdb(pdb, backgroundColor = "pink", highlight = atom.select(pdb, resno=25:28), highlight.style = "spacefill")
```







