---
title: "Class17"
author: "Celia L Ochoa Medina"
format: pdf
---

```{r}
# BiocManager::install("tximport")
# Load the package
library(rhdf5)
library(tximport)

# setup the folder and filenames to read
folders <- list.files(pattern = "_quant")
files <- file.path(folders, "/abundance.h5")

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```



```{r}
names(files) <- folders
files
```

```{r}
head(files)
head(txi.kallisto$counts)
```

```{r}
colSums(txi.kallisto$counts)
```


```{r}
sum(rowSums(txi.kallisto$counts)>0)
```
```{r}
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
```

```{r}
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```


#now make PCA
```{r}
pca <- prcomp(t(x), scale=TRUE)
summary(pca)
```



```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)

```
```{r}
library(ggplot2)
library(ggrepel)
```
```{r}
pca_df <- data.frame(pca$x)
mycols <- c("coral","coral","turquoise","turquoise")

```
```{r}

ggplot(pca_df, aes(x = PC1, y = PC2)) +
  geom_point(aes(color = mycols)) + 
  xlab("PC1") + ylab("PC2") +
  ggtitle("PCA Plot") +
  geom_label_repel(label = rownames(pca_df), col = mycols) +
  theme_minimal()

```

```{r}
ggplot(pca_df, aes(x = PC3, y = PC4)) +
  geom_point(aes(color = mycols)) + 
  xlab("PC3") + ylab("PC4") +
  ggtitle("PCA Plot") +
  geom_label_repel(label = rownames(pca_df), col = mycols) +
  theme_minimal()

```

